# Generated by Django 3.2.17 on 2023-03-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0003_auto_20230302_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
